# compile markdown README to pdf for printing
language: r
pandoc_version: 2.0.6
sudo: required
cache:
  packages: yes

install:
  - R -e "install.packages(c('rmarkdown','knitr'))"
  - mkdir ~/tmp && cd ~/tmp
  - git clone https://${GH_TOKEN}@github.com/khufkens/paper_writing_template.git .

script:
  - R -e "rmarkdown::render('./template.Rmd')"
  
after_success:
  - git add *.pdf
  - git commit -am "[skip travis] update pdf (travis build ${TRAVIS_BUILD_NUMBER})"
  - git push -f origin master

env:
  global:
    secure: "wzz9SclFqQjNvHlGtbqBjvZES3tYXvg6vXWw/fZqjhrqz0QnKt/rR/1C9s1WF/7aPzdZ1+d2jM0tSVLaAam3+jQl5WJ1AA+o+47MFIVugomi+h2aLmKaZegXlFaUe6W0ehLK9K/tPTgiuxwcgMXw7eQQi70aKFtg068KxwNijksMXUxLTLZ7RmlpH8XN4wEutSKfzCtjrWnts3e90cEjqaGTO0KY1mMYHJtVZifGAZU6//AFIeUVwzXK1pCQga9zFujMwE/Gyjay3U685g/SYYEqMoeysCEbl/ISCiUKwKY0Zp3LRWW+shJ47BS9bo5CmrqZLyM0EwMp0ymCtwoPHUDFbvUmHXaOqEfCiV3xpUA5ihdZ8x0oDi+2gL7C0LqynjKQQa/5aF6lcOroUlt+BId5VqJdJo557bQqNSFGgSzhav0EA30MfZlZk99kqLsho8+zKeLP3H/N4GRMdPh6xnl9UP+psxX33A11qVsZPlc+kY5PMk3taFz2px3SiRi13/lSIS2zr4As4Z+Tv0bBmlZuSFoeozlsCGBA2SsUBcx5Um+yZraXF2ToDQqdawKUcMjHKJPdlAwb1GazbFHA4AQm/zIj4iVe0crkmp1ERg+eqalxr7FjuYAACiRqxr+4RtTgluZdlGfFm9Vo+3MwoAHBJ08VNW4PJ4HzxPDWc/g="