# compile markdown README to pdf for printing
language: r
pandoc_version: 2.0.6
sudo: required
cache:
  packages: yes

install:
  - R -e "install.packages(c('rmarkdown','knitr'))"
  - mkdir ~/tmp && cd ~/tmp
  - git clone https://${GH_TOKEN}@github.com/khufkens/paper_template.git .

script:
  - R -e "rmarkdown::render('./template.Rmd')"
  
after_success:
  - git add *.pdf
  - git commit -am "[skip travis] update pdf (travis build ${TRAVIS_BUILD_NUMBER})"
  - git push -f origin master

env:
  global:
    secure: "407quSdqrjCF0Bm2oi+LBKM4YYDiL6SZ0HSYURP0B8scpWn2NDFnnGfD+JXLpDEgWWIpxnStynIVyitHAEYQcy4hAP1Iu6aDeDGvZzB6ca68Rfacs75n8xz2nbtS84tPmno5c0xGFHSSMYltv4eJhNKsYz0plE90Vi3JV5MQ/Sa8gCfJQiN+yrU7yAz0Lnqg6foLMuL7J0sOT/lOZn1bCj1E/sbI0Bsr+JSwhCY9MLSjiK6PlOtetaXf1SGnV7ObEg5FvxxTW94/zBnwVganY4DeYpps2+DtGmz3LTQN4Mmr3s3KQOB1omBcd5BmR1nQUY3gEtPp4U33oVZiEGkifL9Qe5KCSYFmnJo2MW1mwUgzExWTdW2Jf3pcGQD0W5KhJQVdJ3U5tNgFfeu/y595DuMKSkPXRX9r79v/b9hOl2yNP3AG7G/67psB6aed8rvt/9o2NBiHUWATF9paqSshisEpAi45HWB0uJr8X/5QWDIxYd3M3lFFG7JrfqtxdQLieBUFil463eMx1GdxLXqMbBev4swP3YJ4YkQje32PFQ79W0yAYu2fbmMvhqiUvEf5TNqlzoUeYAn+0kzoyev8FYm+rIXx9wVkyZYv5jcak+AidCclbJb1Zh21F6v9LYt89+Ycx1w26+24wcjZqulqjLCDjQHP/BURwNnbHfnTH40="
